from typing import Annotated, Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator


ParameterValue = Annotated[float, Field(ge=-1, le=1)]
HuskinessValue = Annotated[float, Field(ge=-20, le=20)]
IntonationValue = Annotated[float, Field(ge=0, le=2)]
PitchValue = Annotated[float, Field(ge=-600, le=600)]
SpeedValue = Annotated[float, Field(ge=0.2, le=5)]
VolumeValue = Annotated[float, Field(ge=-8, le=8)]
PhonemeDurationValue = Annotated[float, Field(ge=-1, le=10)]


class SpeechSynthesisGlobalParameters(BaseModel):
    model_config = ConfigDict(extra="allow")

    alp: Optional[ParameterValue] = Field(
        default=None,
        description="Age-like parameter.",
    )
    huskiness: Optional[HuskinessValue] = Field(
        default=None,
        description="Huskiness control parameter.",
    )
    intonation: Optional[IntonationValue] = Field(
        default=None,
        description="Scale factor for pitch contour variation.",
    )
    pitch: Optional[PitchValue] = Field(
        default=None,
        description="Pitch shift coefficient described in cents.",
    )
    speed: Optional[SpeedValue] = Field(
        default=None,
        description="Speed parameter.",
    )
    style_weights: Optional[list[float]] = Field(
        default=None,
        description="Style weights for the selected voice.",
    )
    volume: Optional[VolumeValue] = Field(
        default=None,
        description="Amplitude multiplier described in decibels.",
    )


class SpeechSynthesisRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={
            "anyOf": [
                {
                    "required": ["analyzed_text"],
                    "properties": {
                        "analyzed_text": {"type": "string", "minLength": 1},
                        "text": {"type": "string", "default": ""},
                    },
                },
                {
                    "required": ["text"],
                    "properties": {
                        "text": {"type": "string", "minLength": 1},
                    },
                },
            ],
            "examples": [
                {
                    "text": "こんにちは！音声合成のテストです。",
                    "language": "ja_JP",
                    "voice_name": "tanaka-san_ja_JP",
                    "voice_version": "2.0.1",
                    "global_parameters": {
                        "alp": 0.0,
                        "huskiness": 0.0,
                        "intonation": 1.0,
                        "pitch": 0.0,
                        "speed": 1.0,
                        "style_weights": [],
                        "volume": 0.0,
                    },
                }
            ]
        },
    )

    language: str = Field(
        description="Language code for synthesis, usually selected from the voice library.",
        examples=["ja_JP"],
    )
    text: Optional[str] = Field(
        default=None,
        max_length=500,
        description=(
            "Text for speech synthesis. Required unless a non-empty analyzed_text is set."
        ),
        examples=["こんにちは"],
    )
    analyzed_text: Optional[str] = Field(
        default=None,
        max_length=50000,
        description=(
            "Analyzed text generated by text analysis. If non-empty, text is ignored "
            "in speech synthesis."
        ),
    )
    voice_name: Optional[str] = Field(
        default=None,
        description="Voice library name.",
        examples=["tanaka-san_ja_JP"],
    )
    voice_version: Optional[str] = Field(
        default=None,
        description="Voice library version.",
        examples=["2.0.1"],
    )
    global_parameters: Optional[SpeechSynthesisGlobalParameters] = Field(
        default=None,
        description="Global voice parameters.",
    )

    destination: Optional[Literal["audio_device", "file", "memory"]] = Field(
        default=None,
        description=(
            "Accepted for upstream API compatibility, but ignored by the proxy. "
            "The proxy always sends destination='file' upstream."
        ),
    )
    output_file_path: Optional[str] = Field(
        default=None,
        description=(
            "Accepted for upstream API compatibility, but ignored by the proxy. "
            "The proxy always sends its internal cache path upstream."
        ),
    )
    force_enqueue: Optional[bool] = Field(
        default=None,
        description=(
            "Accepted for upstream API compatibility, but ignored by the proxy. "
            "The proxy always sends force_enqueue=true upstream."
        ),
    )
    can_overwrite_file: Optional[bool] = Field(
        default=None,
        description=(
            "Accepted for upstream API compatibility, but ignored by the proxy. "
            "The proxy always sends can_overwrite_file=true upstream."
        ),
    )
    phoneme_durations: Optional[list[PhonemeDurationValue]] = Field(
        default=None,
        description=(
            "Requested phoneme durations in seconds. Negative values mean automatic."
        ),
    )

    @model_validator(mode="after")
    def validate_synthesis_text(self):
        if self.analyzed_text or self.text:
            return self
        raise ValueError("Either text or analyzed_text must be set")

    def to_payload(self) -> dict[str, Any]:
        return self.model_dump(exclude_none=True)
